/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "davkyxvojuggbyvpdjpm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhdmt5eHZvanVnZ2J5dnBkanBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczODI5MzQsImV4cCI6MjA4Mjk1ODkzNH0.H1eJ-IXaXLrxvndYdKgHAiL7vixOgv9pLj4-9EIs9PE"